const reservationList = [
  {
    id: 1,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Time Left to Pay",
    time: "20:59",
    statusType: "gray",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
    statusIcon: "/images/lock.svg",
    alarmIcon: "/images/alarm.svg",
  },
  {
    id: 2,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected1: "/images/stayhub-f.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "stayhub",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Cancelled",
    statusType: "gray",
    mobileIcon: "/images/mobile.svg",
    statusIcon: "/images/close.svg",
    note: "/images/readnote.svg",
    walletIcon: "/images/wallet.svg",
  },
  {
    id: 3,
    apartment: "1 Bed Room Apartment – Cozy Living",

    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Confirmed",
    statusType: "blue",
    mobileIcon: "/images/mobile.svg",
    statusIcon: "/images/confirm.svg",
    note: "/images/graynote.svg",
  },
  {
    id: 4,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected1: "/images/stayhub-f.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "stayhub",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Time Left to Verify",
    statusIcon: "/images/lock.svg",
    time: "20:59",
    statusType: "gray",
    statusIcon: "/images/lock.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
    alarmIcon: "/images/alarm.svg",
    walletIcon: "/images/wallet.svg",
  },
  {
    id: 5,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Cancelled",
    statusType: "red",
    statusIcon: "/images/close.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 6,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Confirmed",
    statusType: "blue",
    statusIcon: "/images/confirm.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 7,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "stayhub",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Time Left to Pay",
    time: "20:59",
    statusType: "gray",
    statusIcon: "/images/lock.svg",
    alarmIcon: "/images/alarm.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 8,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected1: "/images/stayhub-f.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "stayhub",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Cancelled",
    statusType: "red",
    statusIcon: "/images/close.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 9,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Confirmed",
    statusType: "gray",
    statusIcon: "/images/confirm.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 10,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected1: "/images/stayhub-f.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "stayhub",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Time Left to Pay",
    time: "20:59",
    statusType: "gray",
    statusIcon: "/images/lock.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 11,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Cancelled",
    statusType: "red",
    statusIcon: "/images/close.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 12,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected1: "/images/stayhub-f.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "stayhub",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Confirmed",
    statusType: "gray",
    statusIcon: "/images/confirm.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 13,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected1: "/images/stayhub-f.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Time Left to Pay",
    time: "20:59",
    statusType: "gray",
    statusIcon: "/images/lock.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
    alarmIcon: "/images/alarm.svg",
  },
  {
    id: 14,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "Reception",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Cancelled",
    statusType: "red",
    statusIcon: "/images/close.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
  {
    id: 15,
    apartment: "1 Bed Room Apartment – Cozy Living",
    selected2: "/images/office.svg",
    guestName: "Mohammed Al-Saud",
    reservationNo: "441805916",
    reservationType: "stayhub",
    unitNo: "C0003",
    checkIn: "19/Feb/2025",
    checkOut: "20/Feb/2025",
    status: "Reservation Confirmed",
    statusType: "blue",
    statusIcon: "/images/confirm.svg",
    mobileIcon: "/images/mobile.svg",
    note: "/images/readnote.svg",
  },
];
export default reservationList;
